### ISSUE TITLE
Heron-handoff Plugin stopped working after Figma and mac Update 

### ISSUE THREAD

**Issue by istokk** [hallee9000/heron-handoff#80]
<img width="345" alt="Bildschirmfoto 2024-08-21 um 09 16 26" src="https://github.com/user-attachments/assets/958d2544-533d-4e5d-ac6d-705d7a4abfd2">

After the update to the latest version of Figma and to macOS Sonoma 14.6.1 the Plugin stopped working.
Figma Desktop App version 124.3.1

It also doesn't work in the Browser.

Even when trying to export one Frame with only one rectangle the process starts and stops at the step shown in the screenshot. It doesn't continue.

Would be very thankful for help on this.

**Comment by hallee9000** [comment]
I just published a new version to fix it. Could you try if it's fixed?

**Comment by istokk** [comment]
Thank you so much! It is fixed now! Don't drink all the coffee at once ;) - And btw - it's a great plugin! Offline workflow is still needed in some projects....

**Comment by gbeeri613** [comment]
Hi! Love the plugin, it's invaluable for my work.
Unfortuanately it seems that the fix has not resolved the bug for me, and I am not able to get the plugin to work no matter what - on web, desktop, windows, I even tried it in figma running on an android tablet. the moment I press "Start Generating" everything freezes, and I need top kill figma altogether to escape the frozen state.

**Comment by jaapknoester** [comment]
Dear @hallee9000, love the plugin! For me (Figma Desktop App, version 125.0.8, latest Heron version, Apple M1 Pro) the plugin recently gets stuck at 'creating css'. Any idea why and/or potential fixes in the pipeline? Thanks!
